from __future__ import annotations

from collections import Counter
from datetime import datetime
from pathlib import Path
from typing import Any


def write_packing_report(result_data: dict[str, Any], path: Path) -> Path:
    Workbook, Alignment, Border, Font, PatternFill, Side = _load_openpyxl()

    workbook = Workbook()
    summary_sheet = workbook.active
    summary_sheet.title = "Упаковочный лист"
    manual_sheet = workbook.create_sheet("Ручное заполнение", 1)
    details_sheet = workbook.create_sheet("Отправочные места")

    placed_rows = _placed_rows(result_data)
    unplaced_rows = _unplaced_rows(result_data)

    _build_summary_sheet(
        sheet=summary_sheet,
        placed_rows=placed_rows,
        unplaced_rows=unplaced_rows,
        result_data=result_data,
        alignment_cls=Alignment,
        border_cls=Border,
        font_cls=Font,
        fill_cls=PatternFill,
        side_cls=Side,
    )
    _build_manual_sheet(
        sheet=manual_sheet,
        placed_rows=placed_rows,
        result_data=result_data,
        alignment_cls=Alignment,
        border_cls=Border,
        font_cls=Font,
        fill_cls=PatternFill,
        side_cls=Side,
    )
    _build_details_sheet(
        sheet=details_sheet,
        placed_rows=placed_rows,
        result_data=result_data,
        alignment_cls=Alignment,
        border_cls=Border,
        font_cls=Font,
        fill_cls=PatternFill,
        side_cls=Side,
    )

    workbook.properties.creator = "packing-mvp"
    workbook.properties.title = "Packing Report"
    workbook.properties.description = "Generated by packing-mvp."

    output_path = Path(path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    workbook.save(output_path)
    return output_path


def _build_summary_sheet(
    *,
    sheet: Any,
    placed_rows: list[dict[str, Any]],
    unplaced_rows: list[dict[str, Any]],
    result_data: dict[str, Any],
    alignment_cls: Any,
    border_cls: Any,
    font_cls: Any,
    fill_cls: Any,
    side_cls: Any,
) -> None:
    styles = _styles(
        alignment_cls=alignment_cls,
        border_cls=border_cls,
        font_cls=font_cls,
        fill_cls=fill_cls,
        side_cls=side_cls,
    )
    truck = result_data.get("truck") or {}
    used = result_data.get("used_extents_mm") or {}
    status_text = "Успешно" if result_data.get("success") else "Не все места размещены"

    sheet.merge_cells("A1:G1")
    sheet["A1"] = "Упаковочный лист"
    sheet["A1"].font = styles["title_font"]
    sheet["A1"].alignment = styles["title_alignment"]

    sheet.merge_cells("A2:G2")
    sheet["A2"] = "Шапка отчёта изменяется: при необходимости реквизиты заполняются вручную."
    sheet["A2"].font = styles["note_font"]
    sheet["A2"].alignment = styles["wrap_alignment"]

    info_rows = (
        ("Дата формирования", datetime.now().strftime("%Y-%m-%d %H:%M")),
        ("Статус", status_text),
        ("Размещено мест", int(result_data.get("packed_count") or 0)),
        ("Неразмещено мест", int(result_data.get("unpacked_count") or 0)),
        ("Кузов (мм)", _truck_dims_text(truck)),
        ("Использовано (мм)", _used_dims_text(used)),
    )
    for row_index, (label, value) in enumerate(info_rows, start=4):
        sheet[f"A{row_index}"] = label
        sheet[f"A{row_index}"].font = styles["label_font"]
        sheet[f"B{row_index}"] = value
        sheet[f"B{row_index}"].alignment = styles["wrap_alignment"]

    table_row = 11
    headers = (
        "№ места",
        "Наименование",
        "Тип",
        "Габариты места (мм)",
        "Положение в кузове (мм)",
        "Поворот",
        "Источник",
    )
    _write_table_header(sheet=sheet, row_index=table_row, headers=headers, styles=styles)

    next_row = table_row + 1
    if placed_rows:
        for row in placed_rows:
            values = (
                row["place_no"],
                row["name"],
                row["source_kind_label"],
                row["dims_text"],
                row["position_text"],
                row["rotation"],
                row["source_label"],
            )
            _write_row(sheet=sheet, row_index=next_row, values=values, styles=styles)
            next_row += 1
    else:
        sheet.merge_cells(start_row=next_row, start_column=1, end_row=next_row, end_column=7)
        sheet.cell(next_row, 1).value = "Размещённые места отсутствуют."
        sheet.cell(next_row, 1).alignment = styles["wrap_alignment"]
        sheet.cell(next_row, 1).border = styles["cell_border"]
        next_row += 1

    if unplaced_rows:
        next_row += 2
        sheet[f"A{next_row}"] = "Неразмещённые типы"
        sheet[f"A{next_row}"].font = styles["section_font"]
        next_row += 1
        _write_table_header(
            sheet=sheet,
            row_index=next_row,
            headers=("Наименование", "Количество", "Источник"),
            styles=styles,
        )
        next_row += 1
        for row in unplaced_rows:
            _write_row(
                sheet=sheet,
                row_index=next_row,
                values=(row["name"], row["quantity"], row["source_label"]),
                styles=styles,
            )
            next_row += 1

    sheet.freeze_panes = f"A{table_row + 1}"
    sheet.auto_filter.ref = f"A{table_row}:G{max(table_row + 1, table_row + len(placed_rows))}"
    _apply_sheet_layout(
        sheet=sheet,
        widths={
            "A": 12,
            "B": 34,
            "C": 14,
            "D": 20,
            "E": 26,
            "F": 14,
            "G": 48,
        },
    )


def _build_manual_sheet(
    *,
    sheet: Any,
    placed_rows: list[dict[str, Any]],
    result_data: dict[str, Any],
    alignment_cls: Any,
    border_cls: Any,
    font_cls: Any,
    fill_cls: Any,
    side_cls: Any,
) -> None:
    styles = _styles(
        alignment_cls=alignment_cls,
        border_cls=border_cls,
        font_cls=font_cls,
        fill_cls=fill_cls,
        side_cls=side_cls,
    )

    sheet.merge_cells("A1:K1")
    sheet["A1"] = "Лист для ручного заполнения"
    sheet["A1"].font = styles["title_font"]
    sheet["A1"].alignment = styles["title_alignment"]

    sheet.merge_cells("A2:K2")
    sheet["A2"] = (
        "Номера мест и габариты заполнены автоматически. "
        "Содержимое, вес и примечания можно перенести вручную из конструкторского Excel."
    )
    sheet["A2"].font = styles["note_font"]
    sheet["A2"].alignment = styles["wrap_alignment"]

    truck = result_data.get("truck") or {}
    sheet["A4"] = "Кузов (мм)"
    sheet["A4"].font = styles["label_font"]
    sheet["B4"] = _truck_dims_text(truck)
    sheet["B4"].alignment = styles["wrap_alignment"]

    headers = (
        "№ места",
        "item_id",
        "Наименование места",
        "Источник",
        "Габариты места (мм)",
        "Всего мест типа",
        "Содержимое",
        "Вес, кг",
        "Количество в месте",
        "Габариты из КД",
        "Примечание",
    )
    header_row = 6
    _write_table_header(sheet=sheet, row_index=header_row, headers=headers, styles=styles)

    next_row = header_row + 1
    if placed_rows:
        for row in placed_rows:
            values = (
                row["place_no"],
                row["item_id"],
                row["name"],
                row["source_label"],
                row["dims_text"],
                row["type_total_quantity"],
                None,
                None,
                None,
                None,
                None,
            )
            _write_row(sheet=sheet, row_index=next_row, values=values, styles=styles)
            next_row += 1
    else:
        sheet.merge_cells(start_row=next_row, start_column=1, end_row=next_row, end_column=11)
        sheet.cell(next_row, 1).value = "Размещённые места отсутствуют."
        sheet.cell(next_row, 1).alignment = styles["wrap_alignment"]
        sheet.cell(next_row, 1).border = styles["cell_border"]

    sheet.freeze_panes = f"A{header_row + 1}"
    sheet.auto_filter.ref = f"A{header_row}:K{max(header_row + 1, header_row + len(placed_rows))}"
    _apply_sheet_layout(
        sheet=sheet,
        widths={
            "A": 12,
            "B": 18,
            "C": 28,
            "D": 36,
            "E": 20,
            "F": 16,
            "G": 32,
            "H": 12,
            "I": 18,
            "J": 20,
            "K": 26,
        },
    )


def _build_details_sheet(
    *,
    sheet: Any,
    placed_rows: list[dict[str, Any]],
    result_data: dict[str, Any],
    alignment_cls: Any,
    border_cls: Any,
    font_cls: Any,
    fill_cls: Any,
    side_cls: Any,
) -> None:
    styles = _styles(
        alignment_cls=alignment_cls,
        border_cls=border_cls,
        font_cls=font_cls,
        fill_cls=fill_cls,
        side_cls=side_cls,
    )

    sheet.merge_cells("A1:L1")
    sheet["A1"] = "Отправочные места"
    sheet["A1"].font = styles["title_font"]
    sheet["A1"].alignment = styles["title_alignment"]

    sheet.merge_cells("A2:L2")
    sheet["A2"] = "Нумерация начинается с первого места и идёт по порядку расположения в кузове."
    sheet["A2"].font = styles["note_font"]
    sheet["A2"].alignment = styles["wrap_alignment"]

    truck = result_data.get("truck") or {}
    sheet["A4"] = "Кузов (мм)"
    sheet["A4"].font = styles["label_font"]
    sheet["B4"] = _truck_dims_text(truck)
    sheet["B4"].alignment = styles["wrap_alignment"]

    headers = (
        "№ места",
        "item_id",
        "instance_id",
        "Наименование",
        "X",
        "Y",
        "Z",
        "L",
        "W",
        "H",
        "Поворот",
        "Источник",
    )
    header_row = 6
    _write_table_header(sheet=sheet, row_index=header_row, headers=headers, styles=styles)

    next_row = header_row + 1
    if placed_rows:
        for row in placed_rows:
            values = (
                row["place_no"],
                row["item_id"],
                row["instance_id"],
                row["name"],
                row["x"],
                row["y"],
                row["z"],
                row["l"],
                row["w"],
                row["h"],
                row["rotation"],
                row["source_label"],
            )
            _write_row(sheet=sheet, row_index=next_row, values=values, styles=styles)
            next_row += 1
    else:
        sheet.merge_cells(start_row=next_row, start_column=1, end_row=next_row, end_column=12)
        sheet.cell(next_row, 1).value = "Размещённые места отсутствуют."
        sheet.cell(next_row, 1).alignment = styles["wrap_alignment"]
        sheet.cell(next_row, 1).border = styles["cell_border"]

    sheet.freeze_panes = f"A{header_row + 1}"
    sheet.auto_filter.ref = f"A{header_row}:L{max(header_row + 1, header_row + len(placed_rows))}"
    _apply_sheet_layout(
        sheet=sheet,
        widths={
            "A": 12,
            "B": 18,
            "C": 22,
            "D": 30,
            "E": 10,
            "F": 10,
            "G": 10,
            "H": 10,
            "I": 10,
            "J": 10,
            "K": 14,
            "L": 44,
        },
    )


def _write_table_header(*, sheet: Any, row_index: int, headers: tuple[str, ...], styles: dict[str, Any]) -> None:
    for column_index, header in enumerate(headers, start=1):
        cell = sheet.cell(row_index, column_index)
        cell.value = header
        cell.font = styles["header_font"]
        cell.fill = styles["header_fill"]
        cell.border = styles["cell_border"]
        cell.alignment = styles["header_alignment"]


def _write_row(*, sheet: Any, row_index: int, values: tuple[Any, ...], styles: dict[str, Any]) -> None:
    for column_index, value in enumerate(values, start=1):
        cell = sheet.cell(row_index, column_index)
        cell.value = value
        cell.border = styles["cell_border"]
        cell.alignment = styles["wrap_alignment"]


def _apply_sheet_layout(*, sheet: Any, widths: dict[str, float]) -> None:
    for column_name, width in widths.items():
        sheet.column_dimensions[column_name].width = width
    for row_index in range(1, sheet.max_row + 1):
        sheet.row_dimensions[row_index].height = 22


def _styles(*, alignment_cls: Any, border_cls: Any, font_cls: Any, fill_cls: Any, side_cls: Any) -> dict[str, Any]:
    side = side_cls(style="thin", color="C7CED6")
    return {
        "title_font": font_cls(name="Segoe UI", size=16, bold=True),
        "section_font": font_cls(name="Segoe UI", size=12, bold=True),
        "label_font": font_cls(name="Segoe UI", size=10, bold=True),
        "note_font": font_cls(name="Segoe UI", size=10, italic=True, color="5E6B75"),
        "header_font": font_cls(name="Segoe UI", size=10, bold=True, color="FFFFFF"),
        "title_alignment": alignment_cls(horizontal="left", vertical="center"),
        "header_alignment": alignment_cls(horizontal="center", vertical="center", wrap_text=True),
        "wrap_alignment": alignment_cls(horizontal="left", vertical="top", wrap_text=True),
        "header_fill": fill_cls(fill_type="solid", fgColor="2F7A6D"),
        "cell_border": border_cls(left=side, right=side, top=side, bottom=side),
    }


def _placed_rows(result_data: dict[str, Any]) -> list[dict[str, Any]]:
    placed_items = list(result_data.get("placed_items") or [])
    type_totals = _type_totals(result_data=result_data, placed_items=placed_items)
    rows: list[dict[str, Any]] = []
    for index, item in enumerate(_sorted_placed_items(placed_items), start=1):
        position = item.get("position_mm") or {}
        dims = item.get("dimensions_mm") or {}
        item_id = str(item.get("item_id") or "")
        x = _as_number(position.get("x"))
        y = _as_number(position.get("y"))
        z = _as_number(position.get("z"))
        l = _as_number(dims.get("L"))
        w = _as_number(dims.get("W"))
        h = _as_number(dims.get("H"))
        rows.append(
            {
                "place_no": int(item.get("place_no") or index),
                "item_id": item_id,
                "instance_id": str(item.get("instance_id") or ""),
                "name": str(item.get("name") or item_id or "Место"),
                "rotation": str(item.get("rotation") or "XYZ"),
                "source_label": str(item.get("source_path") or "Ручной ящик"),
                "source_kind_label": "Ручной" if item.get("source_kind") == "manual" else "STEP",
                "type_total_quantity": type_totals.get(item_id, 1),
                "x": x,
                "y": y,
                "z": z,
                "l": l,
                "w": w,
                "h": h,
                "dims_text": _dims_text(l, w, h),
                "position_text": _dims_text(x, y, z),
            }
        )
    return rows


def _type_totals(*, result_data: dict[str, Any], placed_items: list[dict[str, Any]]) -> dict[str, int]:
    catalog = result_data.get("catalog") or []
    catalog_totals: dict[str, int] = {}
    if isinstance(catalog, list):
        for item in catalog:
            if not isinstance(item, dict):
                continue
            item_id = str(item.get("item_id") or "")
            quantity = int(item.get("quantity") or 0)
            if item_id and quantity > 0:
                catalog_totals[item_id] = quantity
    if catalog_totals:
        return catalog_totals

    counts = Counter(str(item.get("item_id") or "") for item in placed_items if item.get("item_id"))
    return {item_id: quantity for item_id, quantity in counts.items() if item_id}


def _unplaced_rows(result_data: dict[str, Any]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for item in list(result_data.get("unplaced_items") or []):
        if not isinstance(item, dict):
            continue
        rows.append(
            {
                "name": str(item.get("name") or item.get("item_id") or "Место"),
                "quantity": int(item.get("quantity") or 0),
                "source_label": str(item.get("source_path") or ""),
            }
        )
    return rows


def _sorted_placed_items(placed_items: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return sorted(
        placed_items,
        key=lambda item: (
            _sort_order(item),
            _as_number((item.get("position_mm") or {}).get("x")),
            _as_number((item.get("position_mm") or {}).get("y")),
            _as_number((item.get("position_mm") or {}).get("z")),
            str(item.get("item_id") or ""),
            str(item.get("instance_id") or ""),
        ),
    )


def _sort_order(item: dict[str, Any]) -> int:
    place_no = item.get("place_no")
    if isinstance(place_no, int):
        return place_no
    if isinstance(place_no, float):
        return int(place_no)
    return 10**9


def _truck_dims_text(truck: dict[str, Any]) -> str:
    return _dims_text(
        _as_number(truck.get("length_mm")),
        _as_number(truck.get("width_mm")),
        _as_number(truck.get("height_mm")),
    )


def _used_dims_text(used: dict[str, Any]) -> str:
    return _dims_text(
        _as_number(used.get("L")),
        _as_number(used.get("W")),
        _as_number(used.get("H")),
    )


def _dims_text(first: float, second: float, third: float) -> str:
    return f"{_fmt_number(first)} x {_fmt_number(second)} x {_fmt_number(third)}"


def _fmt_number(value: float) -> str:
    if int(value) == value:
        return str(int(value))
    return f"{value:.3f}".rstrip("0").rstrip(".")


def _as_number(value: Any) -> float:
    if isinstance(value, bool):
        return float(int(value))
    if isinstance(value, (int, float)):
        return float(value)
    return 0.0


def _load_openpyxl() -> tuple[Any, Any, Any, Any, Any]:
    try:
        from openpyxl import Workbook
        from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
    except ImportError as exc:
        raise RuntimeError(
            "openpyxl is required for Excel report export. Install dependencies with 'python -m pip install -e .'"
        ) from exc
    return Workbook, Alignment, Border, Font, PatternFill, Side
