from __future__ import annotations

import os

DEFAULT_GITHUB_REPOSITORY = "mashingaan/packing"
DEFAULT_RELEASE_ASSET_NAME = "PackingMVP-Setup.exe"
DEFAULT_GITHUB_API_BASE_URL = "https://api.github.com"
DEFAULT_UPDATE_REQUEST_TIMEOUT_SECONDS = 15

AUTO_CHECK_FOR_UPDATES = os.getenv("PACKING_MVP_AUTO_UPDATE_CHECK", "1").strip().lower() not in {
    "0",
    "false",
    "no",
}
GITHUB_REPOSITORY = os.getenv("PACKING_MVP_GITHUB_REPO", DEFAULT_GITHUB_REPOSITORY).strip()
RELEASE_ASSET_NAME = os.getenv("PACKING_MVP_RELEASE_ASSET", DEFAULT_RELEASE_ASSET_NAME).strip() or DEFAULT_RELEASE_ASSET_NAME
GITHUB_API_BASE_URL = os.getenv("PACKING_MVP_GITHUB_API_BASE", DEFAULT_GITHUB_API_BASE_URL).rstrip("/")
UPDATE_REQUEST_TIMEOUT_SECONDS = DEFAULT_UPDATE_REQUEST_TIMEOUT_SECONDS
